- hosts: "{{ variable_host | default('play') }}"
  connection: local
  gather_facts: no
  become: no
  vars: {}
  tasks:
  - name: show message
    debug:
      msg: "Hello AWX {{ inventory_hostname }}"


  - name: get secrets
    kubernetes.core.k8s_info:
      kind: Secret
    register: secrets_result

  - name: show secrets
    debug:
      msg: "{{ secrets_result }}" 
