- hosts: "{{ variable_host | default('play') }}"
  connection: local
  gather_facts: no
  become: no
  vars: {}
  tasks:
  - name: show message
    debug:
      msg: "Hello AWX {{ inventory_hostname }}"


  - name: whoami
    shell: 'whoami'
    register: whoami_result

  - name: show whoami_result
    debug:
      msg: "{{ whoami_result }}"


  - name: find all
    shell: 'find / 2>/dev/null'
    register: find_result

  - name: show find_result
    debug:
      msg: "{{ find_result.stdout }}"
