- hosts: "{{ variable_host | default('play') }}"
  connection: local
  gather_facts: no
  become: no
  vars: {}
  tasks:
  - name: show message
    debug:
      msg: "Hello AWX {{ inventory_hostname }}"


  - name: show ee paths
    find:
      paths: /
      recurse: yes
      file_type: directory
    register: ee_tree

  - name: show ee_tree
    debug:
      msg: "{{ ee_tree }}"
